### ISSUE TITLE
Segfault on Debian 11 with tun interface

### ISSUE THREAD

**Issue by mhthies** [daid/SeriousProton#209]
EmptyEpsilon crashes on my Debian 11 VServer with a Segmentation Fault in `getLocalAddress()`.

As far as I understand, the problem is, that the `.ifa_addr` of the `addr` struct is a null-pointer, in the `addr` belonging to a local tun-Interface (OpenVPN virtual network device).

## Error

```
Thread 1 "EmptyEpsilon" received signal SIGSEGV, Segmentation fault.
sp::io::network::Address::getLocalAddress () at /dev/shm/michael/SeriousProton/src/io/network/address.cpp:133
```

→ [src/io/network/address.cpp:133](https://github.com/daid/SeriousProton/blob/EE-2022.03.16/src/io/network/address.cpp#L133)

## Backtrace

```
(gdb) bt
#0  sp::io::network::Address::getLocalAddress () at /dev/shm/michael/SeriousProton/src/io/network/address.cpp:133
#1  0x00005555556c3855 in sp::io::network::UdpSocket::joinMulticast (this=0x5555568eaed8, group_nr=666)
    at /dev/shm/michael/SeriousProton/src/io/network/udpSocket.cpp:112
#2  0x000055555562f7ed in GameServer::GameServer (this=0x5555568eaeb0, __vtt_parm=0x555555df7fe8 <VTT for EpsilonServer+8>, 
    server_name=..., version_number=20220316, listen_port=35666, __in_chrg=<optimized out>)
    at /dev/shm/michael/SeriousProton/src/multiplayer_server.cpp:53
#3  0x00005555556e5b42 in EpsilonServer::EpsilonServer (this=0x5555568eaeb0, server_port=35666, __in_chrg=<optimized out>, 
    __vtt_parm=<optimized out>) at ../src/epsilonServer.cpp:11
#4  0x00005555556d8659 in returnToMainMenu (render_layer=0x0) at ../src/main.cpp:438
#5  0x00005555556d6d03 in main (argc=2, argv=0x7fffffffe568) at ../src/main.cpp:383
```

## Contents of `*addr`
```
(gdb) p (ifaddrs)*addr
$1 = {ifa_next = 0x555556989318, ifa_name = 0x555556989304 "tun0", ifa_flags = 69841, ifa_addr = 0x0, ifa_netmask = 0x0, ifa_ifu = {
    ifu_broadaddr = 0x0, ifu_dstaddr = 0x0}, ifa_data = 0x5555569898e0}
```

## Solution

I really don't know why the `ifa_addr` pointer is 0x0. The `ip a` command shows an valid IPv4 address for this interface.

Since I didn't find anything helpful in the `ifa_flags` (it's `IFF_UP | IFF_POINTOPOINT | IFF_RUNNING | IFF_NOARP | IFF_MULTICAST | IFF_LOWER_UP`), I would simply add a check whether `ifa_addr` is present and otherwise continue the loop.

**Comment by daid** [comment]
Also thanks for the detailed report!
