### ISSUE TITLE
OSX Build Incompatibility - MSG_NOSIGNAL

### ISSUE THREAD

**Issue by Waagheur** [daid/SeriousProton#252]
The macro MSG_NOSIGNAL is used within the  src/io/network/tcpSocket.cpp and src/io/network/udpSocket.cpp files on non WIN32 builds. However MSG_NOSIGNAL is not supposed to be supported on OSX, and thus will produce "use of undeclared identifier" errors on compilation.

Something akin to :
```
#ifdef __APPLE__
#define MSG_NOSIGNAL 0
#endif
```

Seems to be sufficient to allow building and executing, I am however not versed enough in the networking to know if such a naive fix would not require configuring sockets with setsockopt and SO_NOSIGPIPE to prevent side effects.
I suppose one could also directly set the flags variables to 0 like for WIN32

PS : I know OSX building is very low priority, at worse this might be of some use if someone else wants to build for OSX for some reason

**Comment by daid** [comment]
While apple is indeed low priority, simple build fixes like this never hurt. I think it should be fine now.
