### ISSUE TITLE
Build problems on Linux 

### ISSUE THREAD

**Issue by vslotman** [daid/SeriousProton#4]
Since commit e93db8fa76f95dd6465b9db718efb6b8abcb431b SeriousProton does not compile anymore on Linux. 
Before I had no problems building and running EmptyEpsilon.
I'm using GCC 4.8.3 and SFML 2.3.1 

These are the errors I'm getting:
SeriousProton/src/resources.cpp|48|error: ‘FileInputStream’ in namespace ‘sf’ does not name a type|
SeriousProton/src/resources.cpp||In constructor ‘FileResourceStream::FileResourceStream(string)’:|
SeriousProton/src/resources.cpp|53|error: ‘stream’ was not declared in this scope|
SeriousProton/src/resources.cpp||In member function ‘virtual sf::Int64 FileResourceStream::read(void*, sf::Int64)’:|
SeriousProton/src/resources.cpp|66|error: ‘stream’ was not declared in this scope|
SeriousProton/src/resources.cpp||In member function ‘virtual sf::Int64 FileResourceStream::seek(sf::Int64)’:|
SeriousProton/src/resources.cpp|70|error: ‘stream’ was not declared in this scope|
SeriousProton/src/resources.cpp||In member function ‘virtual sf::Int64 FileResourceStream::tell()’:|
SeriousProton/src/resources.cpp|74|error: ‘stream’ was not declared in this scope|
SeriousProton/src/resources.cpp||In member function ‘virtual sf::Int64 FileResourceStream::getSize()’:|
SeriousProton/src/resources.cpp|78|error: ‘stream’ was not declared in this scope|

**Comment by daid** [comment]
Then you're not actually using SFML-2.3.1, as SFML-2.3.1 added the FileInputStream (which was needed for Android support)

Most likely you still have an older version installed on your system.
