### ISSUE TITLE
Allow Cross Domain Origin access to the Web Server

### ISSUE THREAD

**Issue by kwadroke** [daid/SeriousProton#9]
Currently it only supports accessing the JSON page from the same server. Any webpages being served from another webserver (or locally from a file) can not access it due to CORS errors.

The following would need to be added around Line **301** in _src/httpServer.cpp_ to create the necessary header to support Cross Domain access to the JSON files generated by EmptyEpsilon. 

```
reply += "Access-Control-Allow-Origin: *\r\n";
```
Example
http://MyEEServer:8080/get.lua?alert=getAlertLevel()

Can be replicated by downloading https://gist.github.com/kwadroke/6f4aa0837a5be0621552
and accessing it via a browser using a file url (example: file:///home/user/ee_alert_status.html)

**Comment by daid** [comment]
EE also serves files from a "www" directory inside the main folder, using this to serve files instead of file:/// will prevent CORS errors. (Chrome will give you CORS hell no matter what you do if you use local files)

**Comment by kwadroke** [comment]
Ok, Guess I need to read the source some more then. :)
I was testing with Firefox/IceWeasel. Worked fine there.
Closing this.
